# This is a basic workflow to help you get started with Actions

name: Publishing package to pypi.

# Controls when the workflow will run
on: 
  workflow_dispatch:
    branches: [ master ]
  push:
    branches:
      - master

jobs:
  basic:
    runs-on: ubuntu-20.04

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      #----------------------------------------------
      #  -----  install & configure pdm -----
      #----------------------------------------------
      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Publish
        run: pdm publish
