# This is a basic workflow to help you get started with Actions

name: Publishing package to pypi.

# Controls when the workflow will run
on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: pdm-project/setup-pdm@v4
        with:
          token: ${{ secrets.PYPI_TOKEN }}
