name: Pylint

on: 
  pull_request:
    branches:
      - master

jobs:
  basic:
    runs-on: ubuntu-20.04
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true

      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: pdm install
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      # Runs a set of commands using the runners shell
      - name: Run pytest
        run: PYTHONPATH=src/ pdm run python -m pylint --fail-under=9.5 planarenvs

